version: '3.8'

services:
  MaceCalender-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB:  MaceCalenderdb
    networks:
      - MaceCalender

networks:
  MaceCalender: